package engine

import rt "github.com/asalimonov/montygo/runtime"

// Types.
type BuiltinFunction = rt.BuiltinFunction
type CollectStreams = rt.CollectStreams
type CollectString = rt.CollectString
type CollectedStreamEntry = rt.CollectedStreamEntry
type ContextPrintTarget = rt.ContextPrintTarget
type ConversionError = rt.ConversionError
type CrashedError = rt.CrashedError
type Cycle = rt.Cycle
type Date = rt.Date
type DateTime = rt.DateTime
type Dict = rt.Dict
type DisconnectError = rt.DisconnectError
type DisplayFormat = rt.DisplayFormat
type EllipsisType = rt.EllipsisType
type Error = rt.Error
type Exception = rt.Exception
type ExceptionInfo = rt.ExceptionInfo
type ExternalFunction = rt.ExternalFunction
type FileHandle = rt.FileHandle
type FlushingPrintTarget = rt.FlushingPrintTarget
type Frame = rt.Frame
type FrozenSet = rt.FrozenSet
type MountDir = rt.MountDir
type MountDirOptions = rt.MountDirOptions
type MountMode = rt.MountMode
type NamedTuple = rt.NamedTuple
type NotImplementedType = rt.NotImplementedType
type OptionError = rt.OptionError
type Pair = rt.Pair
type Path = rt.Path
type PrintFunc = rt.PrintFunc
type PrintTarget = rt.PrintTarget
type ProtocolError = rt.ProtocolError
type RaisedError = rt.RaisedError
type ResourceError = rt.ResourceError
type RotationError = rt.RotationError
type RuntimeError = rt.RuntimeError
type SessionKilledError = rt.SessionKilledError
type Set = rt.Set
type ShutdownError = rt.ShutdownError
type Stream = rt.Stream
type SyntaxError = rt.SyntaxError
type Time = rt.Time
type TimeDelta = rt.TimeDelta
type TimeZone = rt.TimeZone
type Tuple = rt.Tuple
type Type = rt.Type
type TypeOrigin = rt.TypeOrigin
type TypingError = rt.TypingError
type ValueError = rt.ValueError

// Constants.
const DefaultMaxPrintCollectBytes = rt.DefaultMaxPrintCollectBytes
const DefaultMountMemoryUsageLimit = rt.DefaultMountMemoryUsageLimit
const DisplayMsg = rt.DisplayMsg
const DisplayTraceback = rt.DisplayTraceback
const DisplayTypeMsg = rt.DisplayTypeMsg
const MountOverlay = rt.MountOverlay
const MountReadOnly = rt.MountReadOnly
const MountReadWrite = rt.MountReadWrite
const OriginBuiltin = rt.OriginBuiltin
const OriginHost = rt.OriginHost
const OriginSandbox = rt.OriginSandbox
const Stderr = rt.Stderr
const Stdout = rt.Stdout
const UnlimitedPrintCollect = rt.UnlimitedPrintCollect

// Variables and sentinels.
var Ellipsis = rt.Ellipsis
var ErrCheckoutTimeout = rt.ErrCheckoutTimeout
var ErrDumpIsIdle = rt.ErrDumpIsIdle
var ErrDumpIsSuspended = rt.ErrDumpIsSuspended
var ErrNotFresh = rt.ErrNotFresh
var ErrNotOSCall = rt.ErrNotOSCall
var ErrPoolClosed = rt.ErrPoolClosed
var ErrSessionBusy = rt.ErrSessionBusy
var ErrSessionClosed = rt.ErrSessionClosed
var ErrSessionLost = rt.ErrSessionLost
var ErrSnapshotResumed = rt.ErrSnapshotResumed
var ErrSnapshotStale = rt.ErrSnapshotStale
var ErrTelemetryPresent = rt.ErrTelemetryPresent
var ErrTurnCancelled = rt.ErrTurnCancelled
var NotImplemented = rt.NotImplemented

// Functions.
var BuildMounts = rt.BuildMounts
var DateTimeFromTime = rt.DateTimeFromTime
var Equal = rt.Equal
var ErrorFromException = rt.ErrorFromException
var ExceptionParts = rt.ExceptionParts
var IsSubclass = rt.IsSubclass
var KnownExceptionNames = rt.KnownExceptionNames
var Lines = rt.Lines
var NewCollectStreams = rt.NewCollectStreams
var NewCollectString = rt.NewCollectString
var NewDict = rt.NewDict
var NewFileHandle = rt.NewFileHandle
var NewFrozenSet = rt.NewFrozenSet
var NewMountDir = rt.NewMountDir
var NewProtocolError = rt.NewProtocolError
var NewSet = rt.NewSet
var Raise = rt.Raise
var Repr = rt.Repr
var TimeDeltaFromDuration = rt.TimeDeltaFromDuration
